// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ankxjybkqorfgvlfhiql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFua3hqeWJrcW9yZmd2bGZoaXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjI4NTYsImV4cCI6MjA2MzczODg1Nn0.YohvEiybYLii5_GZajCFNatI8x9GcmJ5ROiMjjiQOHY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);